# Generated by Django 4.0.5 on 2022-06-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_itemamount_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemamount',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
