# Generated by Django 4.0.5 on 2022-06-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_itemamount_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='tags',
            field=models.ManyToManyField(to='planner.tag'),
        ),
    ]
